### 행렬의 정렬

1. np.sort() : 넘파이에서 sort() 호출

2. np.array.sort() : 행렬자체에서 sort() 호출


####  두 방식 sort() 함수의 차이점


1. np.sort() : 원 행렬을 그대로 유지한채 원 행렬의 정렬된 행렬을 반환

2. np.array.sort() : 원 행렬 자체를 정렬한 형태로 변환하며 None을 반환

In [1]:
import numpy as np

origin = np.array([3,1,9,7])
print('원본:', origin)

원본: [3 1 9 7]


In [2]:
# 넘파이 sort
sorted = np.sort(origin)
print('원본:', origin)
print('정리후:', sorted)

원본: [3 1 9 7]
정리후: [1 3 7 9]


In [3]:
# 행렬의 sort
sorted = origin.sort()
print('원본:', origin)
print('정리후:', sorted)

원본: [1 3 7 9]
정리후: None


### 내림차순 정렬 [::-1]

In [4]:
sorted2 = np.sort(origin)[::-1]
print('내림차순 : ',sorted2)

내림차순 :  [9 7 3 1]


[::] - > 모든행과 모든열

### 2차원 이상의 행렬에서

- axis=0 : 행방향 -> 열단위
- axis=1 : 열방향 -> 행단위

In [5]:
arr = np.array([[9, 6, 3],[5, 11, 2]])
arr1 = np.sort(arr)

print(arr1)
arr2 = np.sort(arr,axis=0)
print(arr2)

[[ 3  6  9]
 [ 2  5 11]]
[[ 5  6  2]
 [ 9 11  3]]


In [6]:
?np.sort

####  정렬된 행렬의 인덱스 반환 : argsort()

In [7]:
arr = np.array([3, 8, 2, 5])
print(np.sort(arr))
print(np.argsort(arr))

[2 3 5 8]
[2 0 3 1]


In [8]:
scores = np.array([66, 33, 88, 55, 99])
names = np.array(['홍길동','박길동','맹길동','최길동','김길동'])

idx = np.argsort(scores)[::-1]
for i in idx:
    print(names[i],':',scores[i])

김길동 : 99
맹길동 : 88
홍길동 : 66
최길동 : 55
박길동 : 33
