 # numpy에서 특수행렬을 만드는 함수

 [ 확인 ] python console 에서 간단하게 확인

In [1]:
 import numpy as np
 np.ones(10)
 np.zeros(5)
 np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

  (1) eye(N, M, k, dtype) : 대각선이 1인 대각행렬(항등행렬)
		N:행의 수, M:열의 수,  k:대각의 위치(기본 0)

In [2]:
np.eye(4, dtype=int)
np.eye(4, dtype=int, k=0)
np.eye(4, dtype=int, k=1)
np.eye(4, dtype=int, k=2)
np.eye(4, 3, dtype=int, k=-1)

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

  (2) diag(v, k) 
	- 정방행렬에서 대각 요소가 추출하여 벡터를 만듬
	- 반대로 벡터요소를 대각 요소로 하는 정방행렬을 만듬
    - v:배열, k=대각의 위치(기본 0)	 
	  
	 (*) 정방행렬 : 행과 열의 수가 동일한 행렬

In [3]:
x=np.eye(5,dtype=int)
v=np.diag(x)
v # 1로만 가지고 있는 벡터

x=np.arange(9).reshape(3,3)
x
np.diag(x)
np.diag(x, k=1)
np.diag(x, k=-1)

np.diag(np.diag(x)) # 벡터요소를 대각요소로 하는 정방행렬 만듬

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

# scipy 라이브러리의 sparse 모듈
   - scikit-learn 알고리즘을 구현 할 때 많이 사용하는 모듈 
   - 희소행렬 (sparse matrix) 

In [4]:
import numpy as np
from scipy import sparse

# (1) 4행 4열의 정방행렬을 만들고 그 중 0인 아닌 원소만 추출
b = np.eye(4, dtype=int)
print('배열: \n{}'.format(b))

# sparse.csr_matrix() : 0이 아닌 원소의 인덱스를 저장
sparse_matrix = sparse.csr_matrix(b)
print('CSR 핼렬: \n{}'.format(sparse_matrix))

# (2) 5행 5열의 왼쪽한칸 내려온 대각행렬을 만들고 0이 아닌 요소 추출
b2 = np.eye(5, k=-1, dtype=int)
print(b2)
sparse_matrix2 = sparse.csr_matrix(b2)
print('CSR 핼렬: \n{}'.format(sparse_matrix2))

# (3) 0부터 15까지의 4행 4열 행렬에서 대각요소만 추출
# b3= np.arange(16)+1
# b3 = b3.reshape(4,4)
b3 = np.arange(16).reshape(4,4)
print(b3)
x= np.diag(b3)
print(x)
y = np.diag(x)
print('\n{}'.format(y))
sparse_matrix3 = sparse.csr_matrix(y)
print('CSR 핼렬: \n{}'.format(sparse_matrix3))

# (4) COO 포맷 (Coordinate 포맷) : 희소행렬을 직접 만들 때
# 데이타가 엄청 많은 경우 메모리 공간을 많이 차지하지 않으면서 희소행렬 만들 수 있다
data = np.ones(4)
print(data)

row_indexes=np.arange(4)
col_indexes=np.arange(4)
eye_coo=sparse.coo_matrix(data, (row_indexes,col_indexes))
print('희소행렬\n{}'.format(eye_coo))



배열: 
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
CSR 핼렬: 
  (0, 0)	1
  (1, 1)	1
  (2, 2)	1
  (3, 3)	1
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]]
CSR 핼렬: 
  (1, 0)	1
  (2, 1)	1
  (3, 2)	1
  (4, 3)	1
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 0  5 10 15]

[[ 0  0  0  0]
 [ 0  5  0  0]
 [ 0  0 10  0]
 [ 0  0  0 15]]
CSR 핼렬: 
  (1, 1)	5
  (2, 2)	10
  (3, 3)	15
[1. 1. 1. 1.]
희소행렬
  (0, 0)	1.0
  (0, 1)	1.0
  (0, 2)	1.0
  (0, 3)	1.0
